---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: Install key
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: true

- name: Install VS Code repo 
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode
    state: present

- name: Install VS Code 
  become: true
  ansible.builtin.apt:
    name: code
    state: present